"""Threshold Constants for the Stadium Commander Crowd Analyzer."""

CROWD_MEDIUM_THRESHOLD = 50
CROWD_HIGH_THRESHOLD = 75
CROWD_CRITICAL_THRESHOLD = 90

CONFIDENCE_LOW = 70
CONFIDENCE_MEDIUM = 80
CONFIDENCE_HIGH = 90
CONFIDENCE_CRITICAL = 98
